@URL = https://web-production-e9616.up.railway.app

###
# Obtener todos los usuarios
GET {{URL}}/traer_usuarios

###
# Crear usuario
POST {{URL}}/registrar_usuario
Content-Type: application/json

{
    "nombre": "Pedro",
    "clave": "carlitos.34",
    "email": "carlitos.juarez@gmail.com"
}


###
# Actualizar usuario con id=1
PUT {{URL}}/actualizar_usuario/3
Content-Type: application/json

{
    "nom": "Juan Actualizado",
    "ape": "Tancamon actualizado"
}

###
# Eliminar usuario con id=1
DELETE {{URL}}/eliminar_usuario/2


###################################
#proyecto

###
# Obtener todos los usuarios
GET {{URL}}/traer_usuario

###
# Crear usuario
POST {{URL}}/nuevo_usuario
Content-Type: application/json

{
    "nombre": "Pedro",
    "email": "carlitos.juarez@gmail.com",
    "fecha_nac": "2004-09-15"
}

###
# Eliminar usuario con id=1
DELETE {{URL}}/eliminar_usuarios/3

###
# Obtener todas las publicaciones
Send Request
GET {{URL}}/consulta_publicacion

###
# Obtener una publicacion por id
Send Request
GET {{URL}}/consulta_publicacion/1

###
# Crear publicacion
Send Request
POST {{URL}}/nueva_publicacion
Content-Type: application/json

{
    "usuario_idusuario": 1,
    "nombre": "Milanesa napolitana",
    "imagenes": "milanesa.jpg",
    "tiempo": 45,
    "ingredientes": "carne, pan rallado, huevo, queso, salsa de tomate",
    "receta": "Empanar la carne, freir, agregar salsa y queso, gratinar al horno"
}

###
# Eliminar publicacion con id=1
Send Request
DELETE {{URL}}/eliminar_publicacion/1