@URL = https://web-production-e9616.up.railway.app

###
# Obtener todos los usuarios
GET {{URL}}/traer_usuarios

###
# Crear usuario
POST {{URL}}/registrar_usuario
Content-Type: application/json

{
    "nombre": "Pedro",
    "clave": "carlitos.34",
    "email": "carlitos.juarez@gmail.com"
}


###
# Actualizar usuario con id=1
PUT {{URL}}/actualizar_usuario/3
Content-Type: application/json

{
    "nom": "Juan Actualizado",
    "ape": "Tancamon actualizado"
}

###
# Eliminar usuario con id=1
DELETE {{URL}}/eliminar_usuario/2


###################################
#proyecto

###
# Obtener todos los usuarios
GET {{URL}}/traer_usuario

###
# Crear usuario
POST {{URL}}/registrar_usuario
Content-Type: application/json

{
    "nombre": "Pedro",
    "clave": "carlitos.34",
    "email": "carlitos.juarez@gmail.com"
}